name: 3-tier-app-CI/CD

on:
  push:
    branches:
      - workflow_dispatch
      - master
      - dev
      - testing
      - feature/baseapp

# permissions:
#   id-token: write
#   contents: write
#   security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install frontend Dependencies
        run: |
          cd task-manager-frontend  
          ls | cat simplefile.txt
          npm install

      - name: Install backend Dependencies
        run: |
          cd task-manager-backend 
          ls | cat simplefile.txt
          npm install
