name: 3-tier-app-CI/CD

on:
  push:
    branches:
      - workflow_dispatch
      - master
      - dev]
      - feature/web-app
   

# permissions:
#   id-token: write
#   contents: write
#   security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install frontend Dependencies
        run: |
          cd task-manager-frontend  
          ls | cat simplefile.txt
          npm install

      - name: Install backend Dependencies
        run: |
          cd task-manager-backend 
          ls | cat simplefile.txt
          npm install

      - name: Run frontend unit Tests
        run: |
          cd task-manager-frontend 
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env 
            npm test

      - name: Run backend unit Tests
        run: |
          cd task-manager-backend
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env 
            npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./task-manager-frontend
          push: true
          tags: honeycanada21/frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./task-manager-backend
          push: true
          tags: honeycanada21/backend:latest